spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/capstone
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    hikari:
      username:
        maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/capstone
    username: postgres
    password: db0zzy9433^^
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      # ??? ? ??? ??? ?? (???? create-drop)
    properties:
      hibernate:
        # show_sql: true -> printf ??? sql ??
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  servlet:
    encoding:
      force-response: true
logging.level:
  org.hibernate.SQL: debug
